#!/bin/bash

# Install native dependencies
apt update
apt install -y curl make

# Install Go
VERSION=1.16
FILE=/tmp/go.tar.gz
if [ "$(uname -m)" = 'x86_64' ]; then
    curl -L -o ${FILE} https://golang.org/dl/go${VERSION}.linux-amd64.tar.gz
else
    curl -L -o ${FILE} https://golang.org/dl/go${VERSION}.linux-arm64.tar.gz
fi
tar -C /usr/local -xzf ${FILE}
export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin

# Make release
make release
