#!/bin/bash

# Install bagop
curl -L -o /tmp/bagop "https://github.com/pojntfx/bagop/releases/latest/download/bagop.linux-$(uname -m)"
install /tmp/bagop /usr/local/bin

# Build release
CGO_ENABLED=0 bagop -j "$(nproc)" -b hydrun -x '(android/*|ios/*)' -p "go build -a -ldflags '-extldflags \"-static\"' -o \$DST main.go"
